### ISSUE TITLE
Is there any plan for audio or video recording of the class?

### ISSUE THREAD

**Issue by sunu** [cis198-2016s/slides#2]
Hi,

Thanks a lot for having the slides and homework up on Github. Would love to see video or audio recording of the lectures too.

**Comment by djmally** [comment]
Thanks for the interest! We'll see if we can get our lectures recorded, I've had it done in the past so it should be possible.

**Comment by sunu** [comment]
Awesome!! Thanks a lot.

**Comment by kainino0x** [comment]
@sunu Unfortunately, we won't be able to do recordings, at least currently.

If you're interested in following along with the class, please join the new public discussion group here:
https://groups.google.com/forum/#!forum/cis198-public
