### ISSUE TITLE
Improvement suggestions for 02

### ISSUE THREAD

**Issue by bluss** [cis198-2016s/slides#4]
### slide 11
- Tuple structs have numbered field accessors just like tuples:  for example `c.0, c.1, c.2`
### 18
- > Structs & enums exist on the stack by default, so they may not be recursive.
- You should say that fields of structs and enum variants are stored _inline_ (not via indirection). Where the struct or enum value is stored itself is not under its own control (it may be an element in a vector, for example).
### 29
- while let iterates until the pattern doesn't match.
### 33
- `<'a>` introduces a generic parameter, to be specific, a lifetime parameter called `'a`.
- The explanation of `x: &'a i32` seems strange. It simply means that `x` has type `&'a i32` (a reference to a i32 that outlives `'a`).
- Using the expression _lifetime parameter_ is in general more correct than most uses of _lifetime_. For example, in the title of slice 35.
### 36
- A note that the lifetime parameters outline which output borrows from which input could be useful here. For example, in `p_or_q`, the return value borrows from the input parameter `p`. In `x_or_y`, both input parameters are considered borrowed as long as the return value is alive.
### 37

"Structs can have lifetime parameters" would be good.
### 38

When used in other contexts (for example `T: 'static`) note that `'static` does not mean “is alive for the whole program” but rather that ”`T` _may_ be kept alive (if you store it somewhere) for the whole program”. Just a note, since I know that many learners have trouble with this.

**Comment by terryxsun** [comment]
Thanks for the very detailed feedback! We struggled a lot with how to explain lifetimes so hopefully it's more clear after adding in your suggestions. I definitely didn't think about that detail with `'static`, but it's good to note.

**Comment by bluss** [comment]
Yeah explaining lifetime parameters well is an eternal struggle. Glad you liked the feedback.
